name: Security Scan with Grype
on:
  push:
    branches:
      - main

jobs:
  scan:
    name: Scan Docker Image with Grype
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v4

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      # - name: Build Docker Image
      #   run: |
      #     docker build -t my-app:latest .
      
      - name: Pull Docker Image
        run: |
          docker pull ubuntu:16.04

      # - name: Scanning official kubernetes repository
      #   run: |
      #      git clone https://github.com/kubernetes/kubernetes.git
      #      cd kubernetes
      #      grype dir:. --fail-on Critical

      - name: Scan Image with Grype
        run: |
          grype ubuntu:16.04 --fail-on critical | tee grype-results.txt

      - name: Uploading grype results
        uses: actions/upload-artifact@v4
        with:
          name: grype-results-file
          path: grype-results.txt

