name: Trivy Security Scan

on:
  push:
    branches:
      - main
jobs:
  Securityscan:
    name: Securityscan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: jenkins/jenkins:latest
        with:
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

